name: Publish Atlas on PyPi at every release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install pypa/build
      working-directory: ./src/bioTea
      run: >-
        python -m
        pip install
        -r requirements-dev.txt
        --user
    - name: Build a binary wheel and a source tarball
      working-directory: ./src/bioTea
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
